name: harmoni
description: A privacy-focused YouTube client.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Core
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

  # YouTube
  youtube_explode_dart: ^2.3.0

  # Media
  video_player: ^2.8.1
  audio_service: ^0.18.12

  # Data
  sqflite: ^2.3.0
  dio: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true